[package]
name = "ntFIBER"
version = "0.1.0"
edition = "2021"

{{DLL_FORMAT}}

[dependencies]
dyncvoke = { git = "https://codeberg.org/smukx/Dyncvoke.git", default-features = false, features = [{{DYNCVOKE_FEATURES}}] }
dyncvoke_core = { git = "https://codeberg.org/smukx/Dyncvoke.git" }
data = { git = "https://codeberg.org/smukx/Dyncvoke.git" }
{{DYNCVOKE_EXTRA_DEPS}}

[dependencies.windows-sys]
version = "0.61"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Memory",
    "Win32_System_Threading",
]

{{DEPENDENCIES}}

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
lto = true
