//! Technique registry — the runtime/build-time abstraction over
//! encryption / injection / evasion plugins.
//!
//! The registry itself (`TECHNIQUES`) is generated by `build.rs` from
//! `technique.toml` manifests and included below.

pub mod build_context;
pub mod types;

pub use build_context::BuildContext;
pub use types::*;

pub trait Technique: Send + Sync {
    fn meta(&self) -> &'static TechniqueMeta;
    fn apply(&self, ctx: &mut BuildContext) -> anyhow::Result<()>;
}

/// All techniques discovered at compile time. Populated by `build.rs`.
pub fn all() -> &'static [&'static dyn Technique] {
    REGISTRY
}

include!(concat!(env!("OUT_DIR"), "/registry.rs"));

pub fn find(id: &str) -> Option<&'static dyn Technique> {
    REGISTRY.iter().copied().find(|t| t.meta().id == id)
}

pub fn by_category(cat: Category) -> impl Iterator<Item = &'static dyn Technique> {
    REGISTRY.iter().copied().filter(move |t| t.meta().category == cat)
}
