[package]
name = "ntCRT"
version = "0.1.0"
edition = "2021"

{{DLL_FORMAT}}

[dependencies]
dyncvoke = { git = "https://git.smukx.site/smukx/Dyncvoke", default-features = false, features = [{{DYNCVOKE_FEATURES}}] }
dyncvoke_core = { git = "https://git.smukx.site/smukx/Dyncvoke" }
data = { git = "https://git.smukx.site/smukx/Dyncvoke" }
{{DYNCVOKE_EXTRA_DEPS}}

[dependencies.windows-sys]
version = "0.61"
features = [
    "Win32_Foundation",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_ToolHelp",
]

{{DEPENDENCIES}}

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
lto = true
